ignored = ["github.com/kubeless/kubeless/pkg/functions"]

[[constraint]]
  name = "github.com/kubeless/kubeless"
  version = "0.6.0"

[[constraint]]
  name = "github.com/segmentio/kafka-go"
  version = "0.1.0"

[prune]
  go-tests = true
  unused-packages = true
