ignored = ["github.com/kubeless/kubeless/pkg/functions"]

[[constraint]]
  name = "github.com/argoproj/argo"
  version = "2.2.0"

[[constraint]]
  name = "github.com/kubeless/kubeless"
  version = "0.6.0"

[[constraint]]
  branch = "release-7.0"
  name = "k8s.io/client-go"

[prune]
  go-tests = true
  unused-packages = true
